apiVersion: v1
kind: PersistentVolume
metadata:
  name: brokerstorepv
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/rocketmq/brokerstore
    server: 192.168.101.176
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brokerstorepvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
