apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brokerstorepvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs

