apiVersion: v1
data:
  broker.conf: |-
    rocketmqHome=/opt/rocketmq-4.3.2
    namesrvAddr=localhost:9876
    brokerName=broker-a
    brokerClusterName=DefaultCluster
    brokerId=0
    brokerPermission=6
    defaultTopicQueueNums=4
    autoCreateTopicEnable=true
    clusterTopicEnable=true
    brokerTopicEnable=true
    autoCreateSubscriptionGroup=true
    sendMessageThreadPoolNums=1
    pullMessageThreadPoolNums=20
    queryMessageThreadPoolNums=10
    adminBrokerThreadPoolNums=16
    clientManageThreadPoolNums=32
    consumerManageThreadPoolNums=32
    heartbeatThreadPoolNums=2
    endTransactionThreadPoolNums=12
    flushConsumerOffsetInterval=5000
    flushConsumerOffsetHistoryInterval=60000
    rejectTransactionMessage=false
    fetchNamesrvAddrByAddressServer=false
    sendThreadPoolQueueCapacity=10000
    pullThreadPoolQueueCapacity=100000
    queryThreadPoolQueueCapacity=20000
    clientManagerThreadPoolQueueCapacity=1000000
    consumerManagerThreadPoolQueueCapacity=1000000
    heartbeatThreadPoolQueueCapacity=50000
    endTransactionPoolQueueCapacity=100000
    filterServerNums=0
    longPollingEnable=true
    shortPollingTimeMills=1000
    notifyConsumerIdsChangedEnable=true
    highSpeedMode=false
    commercialEnable=true
    commercialTimerCount=1
    commercialTransCount=1
    commercialBigCount=1
    commercialBaseCount=1
    transferMsgByHeap=true
    maxDelayTime=40
    regionId=DefaultRegion
    registerBrokerTimeoutMills=6000
    slaveReadEnable=false
    disableConsumeIfConsumerReadSlowly=false
    consumerFallbehindThreshold=17179869184
    brokerFastFailureEnable=true
    waitTimeMillsInSendQueue=200
    waitTimeMillsInPullQueue=5000
    waitTimeMillsInHeartbeatQueue=31000
    waitTimeMillsInTransactionQueue=3000
    startAcceptSendRequestTimeStamp=0
    traceOn=true
    enableCalcFilterBitMap=false
    expectConsumerNumUseFilter=32
    maxErrorRateOfBloomFilter=20
    filterDataCleanTimeSpan=86400000
    filterSupportRetry=false
    enablePropertyFilter=false
    compressedRegister=false
    forceRegister=true
    registerNameServerPeriod=30000
    transactionTimeOut=6000
    transactionCheckMax=15
    transactionCheckInterval=60000
    listenPort=10911
    serverWorkerThreads=8
    serverCallbackExecutorThreads=0
    serverSelectorThreads=3
    serverOnewaySemaphoreValue=256
    serverAsyncSemaphoreValue=64
    serverChannelMaxIdleTimeSeconds=120
    serverSocketSndBufSize=131072
    serverSocketRcvBufSize=131072
    serverPooledByteBufAllocatorEnable=true
    useEpollNativeSelector=false
    clientWorkerThreads=4
    clientCallbackExecutorThreads=2
    clientOnewaySemaphoreValue=65535
    clientAsyncSemaphoreValue=65535
    connectTimeoutMillis=3000
    channelNotActiveInterval=60000
    clientChannelMaxIdleTimeSeconds=120
    clientSocketSndBufSize=131072
    clientSocketRcvBufSize=131072
    clientPooledByteBufAllocatorEnable=false
    clientCloseSocketIfTimeout=false
    useTLS=false
    storePathRootDir=/opt/store
    mapedFileSizeCommitLog=1073741824
    mapedFileSizeConsumeQueue=3000000
    enableConsumeQueueExt=false
    mappedFileSizeConsumeQueueExt=50331648
    bitMapLengthConsumeQueueExt=64
    flushIntervalCommitLog=500
    commitIntervalCommitLog=200
    useReentrantLockWhenPutMessage=false
    flushCommitLogTimed=false
    flushIntervalConsumeQueue=1000
    cleanResourceInterval=10000
    deleteCommitLogFilesInterval=100
    deleteConsumeQueueFilesInterval=100
    destroyMapedFileIntervalForcibly=120000
    redeleteHangedFileInterval=120000
    deleteWhen=02
    diskMaxUsedSpaceRatio=75
    fileReservedTime=128
    putMsgIndexHightWater=600000
    maxMessageSize=65536
    checkCRCOnRecover=true
    flushCommitLogLeastPages=4
    commitCommitLogLeastPages=4
    flushLeastPagesWhenWarmMapedFile=4096
    flushConsumeQueueLeastPages=2
    flushCommitLogThoroughInterval=10000
    commitCommitLogThoroughInterval=200
    flushConsumeQueueThoroughInterval=60000
    maxTransferBytesOnMessageInMemory=262144
    maxTransferCountOnMessageInMemory=32
    maxTransferBytesOnMessageInDisk=65536
    maxTransferCountOnMessageInDisk=8
    accessMessageInMemoryMaxRatio=40
    messageIndexEnable=true
    maxHashSlotNum=5000000
    maxIndexNum=20000000
    maxMsgsNumBatch=64
    messageIndexSafe=false
    haListenPort=10912
    haSendHeartbeatInterval=5000
    haHousekeepingInterval=20000
    haTransferBatchSize=32768
    haMasterAddress=
    haSlaveFallbehindMax=268435456
    brokerRole=ASYNC_MASTER
    flushDiskType=ASYNC_FLUSH
    syncFlushTimeout=5000
    messageDelayLevel=1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h
    flushDelayOffsetInterval=10000
    cleanFileForciblyEnable=true
    warmMapedFileEnable=false
    offsetCheckInSlave=false
    debugLockEnable=false
    duplicationEnable=false
    diskFallRecorded=true
    osPageCacheBusyTimeOutMills=1000
    defaultQueryMaxNum=32
    transientStorePoolEnable=false
    transientStorePoolSize=5
    fastFailIfNoBufferInStorePool=false
kind: ConfigMap
metadata:
  name: broker-conf
  namespace: kube-system
