apiVersion: v1
kind: PersistentVolume
metadata:
  name: serverlogpv
  namespace: kube-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/rocketmq/namesrvlog
    server: 192.168.101.176

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serverlogpvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs

